# Generated by Django 5.1 on 2024-09-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "website_user",
            },
        ),
    ]
