# Generated by Django 5.1 on 2024-09-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteuser",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
