# Generated by Django 5.1 on 2024-10-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_store", models.CharField(max_length=255)),
                ("indirizzo", models.CharField(max_length=255)),
                ("citta", models.CharField(max_length=100)),
                ("latitudine", models.FloatField()),
                ("longitudine", models.FloatField()),
            ],
        ),
    ]
